/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.RegistroUsuario;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 *
 * @author Fabian
 */
public class Jfrm_Login extends javax.swing.JFrame {

    /**
     * Creates new form Jfrm_Transaccion_Lista
     */
    public Jfrm_Login() {
        initComponents();
       // --- 1. Configuración para el campo de Usuario ---
    String userPlaceholder = "Ingrese su nombre de usuario";
    Color colorSugerencia = Color.GRAY;
    Color colorNormal = Color.BLACK;

    // Estado inicial del campo de usuario
    jtxt_nombre_usuario.setText(userPlaceholder);
    jtxt_nombre_usuario.setForeground(colorSugerencia);

    jtxt_nombre_usuario.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            // Al hacer clic, borra la sugerencia
            if (jtxt_nombre_usuario.getText().equals(userPlaceholder)) {
                jtxt_nombre_usuario.setText("");
                jtxt_nombre_usuario.setForeground(colorNormal);
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            // Si queda vacío, restaura la sugerencia
            if (jtxt_nombre_usuario.getText().isEmpty()) {
                jtxt_nombre_usuario.setText(userPlaceholder);
                jtxt_nombre_usuario.setForeground(colorSugerencia);
            }
        }
    });

    // --- 2. Configuración para el campo de Clave ---
    String passPlaceholder = "Ingrese su clave";
    
    // Estado inicial del campo de clave
    jPasswordField.setText(passPlaceholder);
    jPasswordField.setForeground(colorSugerencia);
    jPasswordField.setEchoChar((char) 0); // Muestra el texto (no los puntos)

    jPasswordField.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            // Al hacer clic, borra la sugerencia y pone los puntos
            if (new String(jPasswordField.getPassword()).equals(passPlaceholder)) {
                jPasswordField.setText("");
                jPasswordField.setForeground(colorNormal);
                jPasswordField.setEchoChar('•'); // Carácter de ocultación
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            // Si queda vacío, restaura la sugerencia
            if (new String(jPasswordField.getPassword()).isEmpty()) {
                jPasswordField.setText(passPlaceholder);
                jPasswordField.setForeground(colorSugerencia);
                jPasswordField.setEchoChar((char) 0); // Muestra el texto
            }
        }
    });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1IniciarSesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtn_Ingresar = new javax.swing.JButton();
        jtxt_nombre_usuario = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1IniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1IniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1IniciarSesion.setText("Iniciar Sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(jLabel1IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(642, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1IniciarSesion)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbtn_Ingresar.setText("Ingresar");
        jbtn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_IngresarActionPerformed(evt);
            }
        });

        jtxt_nombre_usuario.setForeground(new java.awt.Color(214, 214, 214));
        jtxt_nombre_usuario.setText("juperez");
        jtxt_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombre_usuarioActionPerformed(evt);
            }
        });

        jPasswordField.setText("*************");

        jLabel1.setText("Nombre Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_Ingresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(229, 229, 229))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtxt_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jbtn_Ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_IngresarActionPerformed
        String usuario = jtxt_nombre_usuario.getText();
    String clave = new String(jPasswordField.getPassword()); 

    // Revisamos que no esté vacío o con el texto de placeholder
    if (usuario.isEmpty() || clave.isEmpty() || usuario.startsWith("Ingrese")) {
        JOptionPane.showMessageDialog(this, "Debe ingresar usuario y clave", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 1. Llama al validador
    RegistroUsuario reg = new RegistroUsuario();
    if (reg.validarUsuario(usuario, clave)) {
        
        // --- LOGIN CORRECTO ---
        JOptionPane.showMessageDialog(this, "¡Bienvenido, " + usuario + "!", "Login Exitoso", JOptionPane.INFORMATION_MESSAGE);
        
        // 2. Guardamos el usuario en la variable ESTÁTICA de Jfrm_Transaccion_Lista
        // (Asegúrate de haber movido la variable 'usuarioLogueado' a esa clase)
        Jfrm_Menu.usuarioLogueado = usuario; 
        
        // 3. Abre la ventana principal de transacciones
        Jfrm_Menu ventanaMenu = new Jfrm_Menu(); 
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        
        // 4. Cierra esta ventana de Login
        this.dispose();
        
    } else {
        
        // --- LOGIN INCORRECTO ---
        JOptionPane.showMessageDialog(this, "Usuario o clave incorrectos", "Login Fallido", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jbtn_IngresarActionPerformed

    
    private void jtxt_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombre_usuarioActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfrm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1IniciarSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton jbtn_Ingresar;
    private javax.swing.JTextField jtxt_nombre_usuario;
    // End of variables declaration//GEN-END:variables
}
